# Generated by Django 3.2 on 2023-05-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230426_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={},
        ),
    ]
