# Generated by Django 3.2.19 on 2023-05-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_phonenumber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('------------', 'Please Select'), ('Western Cape', 'Western Cape'), ('Eastern Cape', 'Eastern Cape'), ('Northern Cape', 'Northern Cape'), ('North West', 'North West'), ('Free State', 'Free State'), ('Kwazulu Natal', 'Kwazulu Natal'), ('Gauteng', 'Gauteng'), ('Limpopo Mpumlanga', 'Limpopo Mpumlanga')], default='------------', max_length=28),
        ),
    ]
