# Generated by Django 3.2.19 on 2023-05-25 21:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_content_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=api.models.content_image_thumbnail_path),
        ),
    ]
