# Generated by Django 4.2.2 on 2023-06-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
        ('api', '0003_productcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
