# Generated by Django 4.2.2 on 2023-06-16 09:09

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to=products.models.product_image_path),
        ),
    ]
