# Generated by Django 3.2.19 on 2023-05-25 22:08

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=products.models.product_image_thumb_path),
        ),
    ]
